a = TreeNode.new("A")
b = TreeNode.new("B")
c = TreeNode.new("C")
d = TreeNode.new("D")
e = TreeNode.new("E")
f = TreeNode.new("F")
g = TreeNode.new("G")

a.add_child(b)
a.add_child(c)
a.add_child(d)
b.add_child(e)
b.add_child(f)
c.add_child(g)